const genres = [
  "Avant-Garde",
  "International",
  "Blues",
  "Jazz",
  "Classical",
  "Novelty",
  "Comedy",
  "Old-Time / Historic",
  "Country",
  "Pop",
  "Disco",
  "Rock",
  "Easy Listening",
  "Soul-RnB",
  "Electronic",
  "Sound Effects",
  "Folk",
  "Soundtrack",
  "Funk",
  "Spoken",
  "Hip-Hop",
  "Audio Collage",
  "Punk",
  "Post-Rock",
  "Lo-Fi",
  "Field Recordings",
  "Metal",
  "Noise",
  "Psych-Folk",
  "Krautrock",
  "Jazz: Vocal",
  "Experimental",
  "Electroacoustic",
  "Ambient Electronic",
  "Radio Art",
  "Loud-Rock",
  "Latin America",
  "Drone",
  "Free-Folk",
  "Noise-Rock",
  "Psych-Rock",
  "Bluegrass",
  "Electro-Punk",
  "Radio",
  "Indie-Rock",
  "Industrial",
  "No Wave",
  "Free-Jazz",
  "Experimental Pop",
  "French",
  "Reggae - Dub",
  "Afrobeat",
  "Nerdcore",
  "Garage",
  "Indian",
  "New Wave",
  "Post-Punk",
  "Sludge",
  "African",
  "Freak-Folk",
  "Jazz: Out",
  "Progressive",
  "Alternative Hip-Hop",
  "Death-Metal",
  "Middle East",
  "Singer-Songwriter",
  "Ambient",
  "Hardcore",
  "Power-Pop",
  "Space-Rock",
  "Polka",
  "Balkan",
  "Unclassifiable",
  "Europe",
  "Americana",
  "Spoken Weird",
  "Interview",
  "Black-Metal",
  "Rockabilly",
  "Easy Listening: Vocal",
  "Brazilian",
  "Asia-Far East",
  "N. Indian Traditional",
  "South Indian Traditional",
  "Bollywood",
  "Pacific",
  "Celtic",
  "Be-Bop",
  "Big Band/Swing",
  "British Folk",
  "Techno",
  "House",
  "Glitch",
  "Minimal Electronic",
  "Breakcore - Hard",
  "Sound Poetry",
  "20th Century Classical",
  "Poetry",
  "Talk Radio",
  "North African",
  "Sound Collage",
  "Flamenco",
  "IDM",
  "Chiptune",
  "Musique Concrete",
  "Improv",
  "New Age",
  "Trip-Hop",
  "Dance",
  "Chip Music",
  "Lounge",
  "Goth",
  "Composed Music",
  "Drum & Bass",
  "Shoegaze",
  "Kid-Friendly",
  "Thrash",
  "Synth Pop",
  "Banter",
  "Deep Funk",
  "Spoken Word",
  "Chill-out",
  "Bigbeat",
  "Surf",
  "Radio Theater",
  "Grindcore",
  "Rock Opera",
  "Opera",
  "Chamber Music",
  "Choral Music",
  "Symphony",
  "Minimalism",
  "Musical Theater",
  "Dubstep",
  "Skweee",
  "Western Swing",
  "Downtempo",
  "Cumbia",
  "Latin",
  "Sound Art",
  "Romany (Gypsy)",
  "Compilation",
  "Rap",
  "Breakbeat",
  "Gospel",
  "Abstract Hip-Hop",
  "Reggae - Dancehall",
  "Spanish",
  "Country & Western",
  "Contemporary Classical",
  "Wonky",
  "Jungle",
  "Klezmer",
  "Holiday",
  "Salsa",
  "Nu-Jazz",
  "Hip-Hop Beats",
  "Modern Jazz",
  "Turkish",
  "Tango",
  "Fado",
  "Christmas",
  "Instrumental",
];

export { genres };
