let songs = {
  1: { name: "Song1", genres: ["Rock"], artists: ["Lukas"] },
  2: { name: "Song2", genres: ["Pop"], artists: ["Mario", "Test"] },
  3: { name: "Song3", genres: ["Techno"], artists: ["David"] },
  4: { name: "Song4", genres: ["Rock"], artists: ["Lukas"] },
  5: { name: "Song5", genres: ["Pop", "Rock"], artists: ["Mario"] },
  6: { name: "Song6", genres: ["Techno"], artists: ["David"] },
  7: { name: "Song7", genres: ["Rock"], artists: ["Lukas"] },
  8: { name: "Song8", genres: ["Pop"], artists: ["Mario"] },
  9: { name: "Song9", genres: ["Techno"], artists: ["David"] },
  10: { name: "Song10", genres: ["Rock"], artists: ["Lukas"] },
  11: { name: "Song11", genres: ["Pop"], artists: ["Mario"] },
  12: { name: "Song12", genres: ["Pop"], artists: ["Mario"] },
  13: { name: "Song13", genres: ["Pop"], artists: ["Mario"] },
  14: { name: "Song14", genres: ["Pop"], artists: ["Mario"] },
  15: { name: "Song15", genres: ["Pop"], artists: ["Mario"] },
  16: { name: "Song16", genres: ["Pop"], artists: ["Mario"] },
  17: { name: "Song17", genres: ["Pop"], artists: ["Mario"] },
  18: { name: "Song18", genres: ["Pop"], artists: ["Mario"] },
  19: { name: "Song19", genres: ["Pop"], artists: ["Mario"] },
  20: { name: "Song20", genres: ["Pop"], artists: ["Mario"] },
  21: { name: "Song21", genres: ["Pop"], artists: ["Mario"] },
  22: { name: "Song22", genres: ["Pop"], artists: ["Mario"] },
  23: { name: "Song23", genres: ["Pop"], artists: ["Mario"] },
  24: { name: "Song24", genres: ["Pop"], artists: ["Mario"] },
  25: { name: "Song25", genres: ["Pop"], artists: ["Mario"] },
  26: { name: "Song26", genres: ["Pop"], artists: ["Mario"] },
  27: { name: "Song27", genres: ["Pop"], artists: ["Mario"] },
};

export { songs };
